apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopcart
  labels:
    app: shopcart
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: shopcart
  template:
    metadata:
      labels:
        app: shopcart
    spec:
      restartPolicy: Always
      containers:
      - name: shopcart
        image: cluster-registry:32000/shopcart:1.0
        # image: shopcart
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: redis-creds
                key: uri
        resources:
          limits:
            cpu: "0.25"
            memory: "64Mi"
          requests:
            cpu: "0.10"
            memory: "32Mi"
